apiVersion: v1
kind: ConfigMap
metadata:
  name: azd-env-configmap
data:
  API_ALLOW_ORIGINS: ""
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00b3d5c0-8589-4537-896a-64903b3b37d5;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/"
  AZURE_AKS_CLUSTER_NAME: "aks-z7nmzhah37yks"
  AZURE_CLIENT_ID: "7c00ccda-34ed-455a-9977-f509fa0293a2"
  AZURE_CONTAINER_REGISTRY_ENDPOINT: "crz7nmzhah37yks.azurecr.io"
  AZURE_CONTAINER_REGISTRY_NAME: "crz7nmzhah37yks"
  AZURE_ENV_NAME: "azure-search-openai-demo-aks"
  AZURE_FORMRECOGNIZER_RESOURCE_GROUP: "rg-azure-search-openai-demo-aks"
  AZURE_FORMRECOGNIZER_SERVICE: "cog-fr-z7nmzhah37yks"
  AZURE_KEY_VAULT_ENDPOINT: "https://kv-z7nmzhah37yks.vault.azure.net/"
  AZURE_LOCATION: "westeurope"
  AZURE_OPENAI_CHATGPT_DEPLOYMENT: "chat"
  AZURE_OPENAI_CHATGPT_MODEL: "gpt-35-turbo"
  AZURE_OPENAI_EMB_DEPLOYMENT: "embedding"
  AZURE_OPENAI_EMB_MODEL_NAME: "text-embedding-ada-002"
  AZURE_OPENAI_RESOURCE_GROUP: "rg-azure-search-openai-demo-aks"
  AZURE_OPENAI_SERVICE: "cog-z7nmzhah37yks"
  AZURE_RESOURCE_GROUP: "rg-azure-search-openai-demo-aks"
  AZURE_SEARCH_INDEX: "gptkbindex"
  AZURE_SEARCH_SERVICE: "gptkb-z7nmzhah37yks"
  AZURE_SEARCH_SERVICE_RESOURCE_GROUP: "rg-azure-search-openai-demo-aks"
  AZURE_SERVICEBUS_NAMESPACE: "sb-z7nmzhah37yks"
  AZURE_SERVICEBUS_SKU_NAME: "Standard"
  AZURE_STORAGE_ACCOUNT: "stz7nmzhah37yks"
  AZURE_STORAGE_CONTAINER: "content"
  AZURE_STORAGE_RESOURCE_GROUP: "rg-azure-search-openai-demo-aks"
  AZURE_SUBSCRIPTION_ID: "c154355a-25c1-4d2b-9b32-c312d07cb558"
  AZURE_TENANT_ID: "16b3c013-d300-468d-ac64-7eda0820b6d3"
  OPENAI_API_KEY: ""
  OPENAI_HOST: "azure"
  OPENAI_ORGANIZATION: ""
  REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00b3d5c0-8589-4537-896a-64903b3b37d5;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/"
  SERVICE_API_ENDPOINT_URL: "http://40.119.157.31/api"
  SERVICE_API_IMAGE_NAME: "crz7nmzhah37yks.azurecr.io/azure-search-openai-demo/api-azure-search-openai-demo-aks:azd-deploy-1706893758"
  SERVICE_INDEXER_ENDPOINT_URL: "http://10.0.14.238:80"
  SERVICE_INDEXER_IMAGE_NAME: "crz7nmzhah37yks.azurecr.io/azure-search-openai-demo/indexer-azure-search-openai-demo-aks:azd-deploy-1706893760"
  SERVICE_WEB_IMAGE_NAME: "crz7nmzhah37yks.azurecr.io/azure-search-openai-demo/web-azure-search-openai-demo-aks:azd-deploy-1706893434"

