apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.claimName }}
spec:
    accessModes:
    - ReadWriteMany
    storageClassName: azurefile
    resources:
        requests:
            storage: 5Gi