# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-search-openai-demo-java-aks
metadata:
  template: azure-search-openai-demo-java-aks@1.5.0-alpha
services:
  api:
    project: ../../app/backend
    language: java
    host: aks
    k8s:
      namespace: java-rag-ns
  indexer:
    project: ../../app/indexer
    language: java
    host: aks
    docker:
      path: ./microservice/Dockerfile
    k8s:
      namespace: java-rag-ns
  frontend:
    project: ../../app/frontend
    language: js
    host: aks
    k8s:
      namespace: java-rag-ns
    docker:
      path: ./Dockerfile-aks

infra:
  path: ./infra
  provider: bicep
hooks:
  preprovision:
      windows:
        shell: pwsh
        run: ./scripts/auth_init.ps1
        interactive: true
        continueOnError: false
      posix:
        shell: sh
        run: ./scripts/auth_init.sh
        interactive: true
        continueOnError: false
  postprovision:
    windows:
      shell: pwsh
      run: ./scripts/prepdocs.ps1
      interactive: true
      continueOnError: false
    posix:
      shell: sh
      run: ./scripts/prepdocs.sh
      interactive: true
      continueOnError: false
  predeploy:
    windows:
      shell: pwsh
      run: ./scripts/predeploy.ps1
      interactive: true
      continueOnError: false
    posix:
      shell: sh
      run: ./scripts/predeploy.sh
      interactive: true
      continueOnError: false
  postdeploy:
    windows:
      shell: pwsh
      run: ./scripts/set_ingress_tls.ps1;./scripts/auth_update.ps1
      interactive: true
      continueOnError: false
    posix:
      shell: sh
      run: ./scripts/set_ingress_tls.sh;./scripts/auth_update.sh
      interactive: true
      continueOnError: false
  