apiVersion: v1
kind: Service
metadata:
  name: indexer-service
  namespace: java-rag-ns
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: indexer
