apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: crz7nmzhah37yks.azurecr.io/azure-search-openai-demo/web-azure-search-openai-demo-aks:azd-deploy-1706893434
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: azd-env-configmap
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://backend-service"
            - name: REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING
              value: InstrumentationKey=00b3d5c0-8589-4537-896a-64903b3b37d5;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/
...
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend

