# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-search-openai-demo
metadata:

  template: azure-search-openai-demo-java@1.2.0-alpha
services:
  backend:
    project: ../../app/backend
    language: java
    host: appservice
    hooks:
      prepackage:
        windows:
          shell: pwsh
          run:  cd ../frontend;npm install;npm run build; if not exist ./backend/src/main/resources/static mkdir ./backend/src/main/resources/static; cp -r ./build/* ../backend/src/main/resources/static
          interactive: true
          continueOnError: false
        posix:
          shell: sh
          run:  cd ../frontend;npm install;npm run build; mkdir -p ../backend/src/main/resources/static; cp -r ./build/* ../backend/src/main/resources/static
          interactive: true
          continueOnError: false

hooks:
    postprovision:
      windows:
        shell: pwsh
        run: ./scripts/prepdocs.ps1
        interactive: true
        continueOnError: false
      posix:
        shell: sh
        run: ./scripts/prepdocs.sh
        interactive: true
        continueOnError: false
